# -*- coding: utf-8 -*-
"""Preparação de Dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RwSx6wIsaOrvtCjlo405Rnndydjhf6g0
"""

import pandas as pd

#importacado do arquivo com os dados
df = pd.read_csv('/content/drive/MyDrive/ecommerce_tratado.csv', encoding='utf-8')

print('Analise de dados únicos:\n', df.nunique())
print('Estatísticas dos dados:\n', df.describe())

#Cria campo 'Preco' a partir dos campos 'Reais' e 'Centavos'
df['Preco'] = df['Reais'] + (df['Centavos']/100)

#Remove os campos 'Reais', 'Centavos', 'Condicao' e 'Condicao_Atual'
df = df.drop(['Reais', 'Centavos', 'Condicao', 'Condicao_Atual'], axis=1)

#Cria campos a partir da scala dos campos 'Nota', 'N_Avaliacoes', 'Desconto' e 'Preco'
scaler = MinMaxScaler(feature_range=(0,1))
df['Nota_MinMax'] = scaler.fit_transform(df[['Nota']])
df['N_Avaliacoes_MinMax'] = scaler.fit_transform(df[['N_Avaliacoes']])
df['Desconto_MinMax'] = scaler.fit_transform(df[['Desconto']])
df['Preco_MinMax'] = scaler.fit_transform(df[['Preco']])

#Cria campos nuéricos referente ao campos 'Marca', 'Material' e 'Temporada'
label_encoder = LabelEncoder()
df['Marca_Cod'] = label_encoder.fit_transform(df['Marca'])
df['Material_Cod'] = label_encoder.fit_transform(df['Material'])
df['Temporada_Cod'] = label_encoder.fit_transform(df['Temporada'])

#Cria campo 'Qtd_Vendidos_Cod' numérico referente ao campo 'Qtd_Vendidos' de acordo com sua grandeza
grandezas = {'Nenhum':0,'1':1, '2':2, '3':3, '4':4, '+5': 5, '+25':25, '+50':50, '+100':100, '+1000':1000, '+10mil':10000, '+50mil':50000}
df['Qtd_Vendidos_Cod'] = df['Qtd_Vendidos'].map(grandezas)

#Cria o campo 'Marca_Freq' numérico referente ao campo 'Marca' de acordo com a frequência do valor.
frequencia_marca = df['Marca'].value_counts() / len(df)
df['Marca_Freq'] = df['Marca'].map(frequencia_marca)

#Cria o campo 'Material_Freq' numérico referente ao campo 'Material' de acordo com a frequência do valor.
frequencia_material = df['Material'].value_counts() / len(df)
df['Material_Freq'] = df['Material'].map(frequencia_material)

#Salva dataframe alterado em novo arquivo
df.to_csv('/content/drive/MyDrive/ecommerce_estatisca.csv', index=False)