# -*- coding: utf-8 -*-
"""Visualização de Dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2asuTa6TG9Q1VW01YfvMaIRgKlfDnnN
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

#carrega o conjunto de dados
df = pd.read_csv('/content/drive/MyDrive/ecommerce_estatistica.csv', encoding='utf-8')

#gráfico histograma
plt.figure(figsize=(8,5))
sns.histplot(df['Nota'], bins=30, color="green", alpha=0.8)
plt.xlabel('Nota dos Produtos')
plt.ylabel('Frequência')
plt.title('Histograma - Distribuição de Notas')
plt.show()

#gráfico de dispersão
plt.figure(figsize=(8, 5))
sns.scatterplot(x=df['Preço'], y=df['Nota'], alpha=0.6, color='purple')
plt.xlabel('Preço (R$)')
plt.ylabel('Nota dos Produtos')
plt.title('Dispersão - Nota e Preço')
plt.show()

#mapa de calor
corr = df[['Nota', 'N_Avaliações', 'Preço', 'Qtd_Vendidos_Cod']].corr()
plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5, vmin=-1, vmax=1)
plt.title('Correlações Nota, Nº de Avaliações, Preço e Qtd Vendidas')
plt.show()

#gráfico de barra
plt.figure(figsize=(10, 6))
sns.countplot(x='Temporada', data=df)
plt.title('Quantidade de Produtos por Temporada')
plt.xlabel('Temporada')
plt.ylabel('Quantidade')
plt.xticks(rotation=45)
plt.show()

#gráfico de pizza
x = df['Gênero'].value_counts().index
y = df['Gênero'].value_counts().values
plt.figure(figsize=(12, 12))
plt.pie(y, labels=x, autopct='%1.1f%%', startangle=180)
plt.title('Distribuição de Produtos por Gênero')
plt.show()

#gráfico de densidade
plt.figure(figsize=(8, 6))
sns.kdeplot(df['Preço'], fill=True)
plt.title('Densidade de Preços')
plt.xlabel('Preço (R$)')
plt.ylabel('Densidade')
plt.show()

#gráfico de regressão
plt.figure(figsize=(8, 6))
sns.regplot(x='Preço', y='Qtd_Vendidos_Cod', data=df)
plt.title('Relação entre Preço e Quantidade Vendida')
plt.xlabel('Preço (R$)')
plt.ylabel('Quantidade Vendida')
plt.show()